# Generated by Django 5.2 on 2025-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cartitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], help_text='Optional subscription type', max_length=10, null=True),
        ),
    ]
