# Generated by Django 5.2 on 2025-09-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cartitems_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], help_text='Optional subscription: weekly or monthly', max_length=10, null=True),
        ),
    ]
