# Generated by Django 5.2 on 2025-09-25 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_snack'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.snack'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ingredient'),
        ),
    ]
