# Generated by Django 5.2 on 2025-09-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cartitems_grams_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('once in a week', 'once in a week'), ('twice in a week', 'twice in a week'), ('three times in a week', 'three times in a week'), ('four times in a week', 'four times in a week'), ('five times in a week', 'five times in a week')], help_text='Optional subscription: weekly or monthly', max_length=40, null=True),
        ),
    ]
