# Generated by Django 5.2 on 2025-09-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_subscription_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snack',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10, null=True),
        ),
    ]
