# Generated by Django 5.2 on 2025-10-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_snack_options_alter_order_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('nut', 'Nut'), ('sweet', 'Sweet'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
