# Generated by Django 5.2 on 2025-10-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_nut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_sweet',
            field=models.BooleanField(default=False),
        ),
    ]
